---
title: "Interactive Component Analysis"
author: "Jonas Han (jh3877)"
date: "December 10, 2018"
output: html_document
---

Finally, we added an interactive component built in D3 which can be seen at (https://jonashan90.github.io/nyc_crime_project/)[https://jonashan90.github.io/nyc_crime_project/]. This analysis complements the graphs above by allowing the viewer to subset the stop and frisk data along the time axis, the geographic location and look at the racial breakdown by police precincts (originally we wanted to plot the data by latitude/longitude but the lack of full data for this prevented us). Several trends can be derived from this data. We can see that the stop and frisk program began in east Brooklyn and stayed concentrated there - precincts 73 & 75 had over 10,000 stops in the first full reporting year (2004) and remained at those levels through 2012. We can see looking at the analysis that the vast majority of the suspects in those stops in precinct 73 were black followed by white-Hispanic. (interesting, there appear to be relatively few people identified as black-Hispanic in the dataset). By 2005 the SQF program had begun to move into the Bronx and Harlem, with precinct 40 in South Bronx having about 13000 stops. This precinct showed more Hispanics relative to the number of African-Americans than the precincts in Brooklyn. By 2006 SQF practices had reached Staten Island and East New York. Lower and middle Manhattan remain relatively unscathed throughout the program except for the Times Square district. This may be related to the broken windows policing policy or simply to extra policing in tourist districts or both. In the description for the interactive component, we briefly touch on the story of the lead plaintiff for the class-action suit against stop and frisk (Floyd v City of New York) and note that David Floyd can be counted as a statistic from precinct 43 in the Bronx in 2008. We can see that similar to our previous analysis for a Bronx district his district's suspects were majority-black (as he was) with about 2/3rds Hispanic. Near La Guardia Airport (precincts 109, 115, 110) we can see our first "purple districts" (greater than 10000 stops) with majority-Hispanic stops. Interestingly, precinct 114 just adjacent is majority-black (this is the precinct that includes Rikers Island, although hopefully there weren't many stop and frisks happening there). By 2011, we can see that the program has peaked with more than 30 purple districts in the city, as noted above. As also noted above, there is not a corresponding peak in felonies, major and non-major or misdemeoners. It's an interesting and underexplored part of this analysis as to why the peak occurred. Critics alleged that quotas as driven by the Compustat program may have exacerbated stops made under the stop and frisk program. It would be interesting to know exactly which statistics are tracked under Compustat and see if there was any explanatory factors for the policing spike here. The drop in rates in 2012 was also an interesting data artifact. The court ruling and election of Bill de Blasio didn't happen until 2013, however public backlash to the program had reached high levels by then. The broken windows theory of policing is supposedly about community policing and it would be interesting to know if the level of community activism or outreach affected the amount of stop and frisks on a per-precinct level. By 2013, much of the map is green with only our old friends precincts 73 & 75 still with elevated levels of arrest. As a interactive data visualization tool, this map is fairly limited in what it allows. One thought we had was to unite this dataset with the arrests dataset; however the lack of historic data for arrests before 2013 made this impractical (the program was practically over by then). Interesting points we left out were whether or not a frisk occured whether or not an arrest occurred. As mentioned in the opinion, at least one analysis (the Fagan report) went through the entire list of stops and attempted to classify them into "apparently justified", "apparently unjustified" or "ungeneralizable" based on the UF-250 form that officers were required to fill out after. It would be interesting to incorporate the results of this analysis into the map.
